### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_Radio_Config_Utility#2]
- [ ] Channel override gets it's own drop down for channel of aligned with Set Channel some how
- [x] Autoscan explained or a more descriptive name
- [x] Auto connect explained
- [x] A way to close the serial port
- [x] Visual feedback for connected or disconnected state

**Comment by cfausn** [comment]
Channel override and set channel should use the same drop down, not really enough room for the two of them. Great additions requests though! Merging now.

**Comment by andrewjaykeller** [comment]
Could you maybe stretch out the drop down to be under both?

**Comment by andrewjaykeller** [comment]
Great job adding in the new features!

**Comment by cfausn** [comment]
The way my buttons work I don't think so, because if the mouse is over a dropdown value AND a button both are activated. That's why I strategically placed the OBCI logo in the middle hahaha
